<?php

return [
    'sorted' => 'desc',
    'rules' => [
        'chajinhua' => [
            'name' => '状元',
            'alias_name' => '状元插金花',
            'field_name' => 'chajinhua',
            'point' => 1200,
            'level' => 1200,
            'class' => \Zhangxiangliang\Mooncake\Rules\ChaJinHuaRule::class,
        ],
        'mantanghong' => [
            'name' => '',
            'alias_name' => '满堂红',
            'field_name' => 'mantanghong',
            'point' => 1100,
            'level' => 1100,
            'class' => \Zhangxiangliang\Mooncake\Rules\ManTangHongRule::class,
        ],
        'biandijin' => [
            'name' => '状元',
            'alias_name' => '遍地锦',
            'field_name' => 'biandijin',
            'point' => 1000,
            'level' => 1000,
            'class' => \Zhangxiangliang\Mooncake\Rules\BianDiJinRule::class,
        ],
        'heiliubo' => [
            'name' => '状元',
            'alias_name' => '黑六勃',
            'field_name' => 'heiliubo',
            'point' => 900,
            'level' => 900,
            'class' => \Zhangxiangliang\Mooncake\Rules\HeiLiuBoRule::class,
        ],
        'wuhong' => [
            'name' => '状元',
            'alias_name' => '五红',
            'field_name' => 'wuhong',
            'point' => 800,
            'level' => 800,
            'class' => \Zhangxiangliang\Mooncake\Rules\WuHongRule::class,
        ],
        'wuzi' => [
            'name' => '状元',
            'alias_name' => '五子',
            'field_name' => 'wuzi',
            'point' => 700,
            'level' => 700,
            'class' => \Zhangxiangliang\Mooncake\Rules\WuZiRule::class,
        ],
        'sihong' => [
            'name' => '状元',
            'alias_name' => '四红',
            'field_name' => 'sihong',
            'point' => 600,
            'level' => 600,
            'class' => \Zhangxiangliang\Mooncake\Rules\SiHongRule::class,
        ],
        'duitang' => [
            'name' => '榜眼',
            'alias_name' => '对堂',
            'field_name' => 'duitang',
            'point' => 500,
            'level' => 500,
            'class' => \Zhangxiangliang\Mooncake\Rules\DuiTangRule::class,
        ],
        'sanhong' => [
            'name' => '探花',
            'alias_name' => '三红',
            'field_name' => 'sanhong',
            'point' => 400,
            'level' => 400,
            'class' => \Zhangxiangliang\Mooncake\Rules\SanHongRule::class,
        ],
        'sijin' => [
            'name' => '进士',
            'alias_name' => '四进',
            'field_name' => 'sijin',
            'point' => 300,
            'level' => 300,
            'class' => \Zhangxiangliang\Mooncake\Rules\SiJinRule::class,
        ],
        'erju' => [
            'name' => '举人',
            'alias_name' => '二举',
            'field_name' => 'erju',
            'point' => 200,
            'level' => 200,
            'class' => \Zhangxiangliang\Mooncake\Rules\ErJuRule::class,
        ],
        'yixiu' => [
            'name' => '秀才',
            'alias_name' => '一秀',
            'field_name' => 'yixiu',
            'point' => 100,
            'level' => 100,
            'class' => \Zhangxiangliang\Mooncake\Rules\YiXiuRule::class,
        ],
    ]
];
